### ISSUE TITLE
Failed to initialize the fix-indent-on-paste package

### ISSUE THREAD

**Issue by dcraycheung** [patstew/fix-indent-on-paste#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: macOS 12.0.1
**Thrown From**: [fix-indent-on-paste](https://github.com/patstew/fix-indent-on-paste) package 0.1.1

### Stack Trace

Failed to initialize the fix-indent-on-paste package

```
At Cannot read property 'path' of undefined

TypeError: Cannot read property 'path' of undefined
    at Object.initialize (/packages/fix-indent-on-paste/lib/fix-indent-on-paste.coffee:21:36)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3389872
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3387945)
    at Package.initializeIfNeeded (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3389733)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3390789)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3390367
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3387945)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3390227
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3390170)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:385612)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:915033
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:909639)
    at n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1194943)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1195097
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1193699)
    at Socket.emit (events.js:228:7)
    at Pipe.<anonymous> (net.js:664:12)
```

### Commands

```
     -3:29.3.0 core:paste (input.hidden-input)
  6x -3:24.8.0 core:move-up (input.hidden-input)
  2x -3:23.7.0 core:move-left (input.hidden-input)
     -3:22.6.0 core:move-right (input.hidden-input)
  7x -3:16.7.0 core:move-down (input.hidden-input)
     -3:14.9.0 core:move-up (input.hidden-input)
     -3:13.6.0 editor:move-to-end-of-screen-line (input.hidden-input)
  7x -3:11.5.0 core:select-up (input.hidden-input)
     -3:09.2.0 core:select-left (input.hidden-input)
     -3:04.6.0 editor:newline (input.hidden-input)
     -3:03.6.0 core:move-up (input.hidden-input)
     -3:03.3.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -3:03.0 editor:newline (input.hidden-input)
     -3:02.8.0 core:paste (input.hidden-input)
  2x -2:43.6.0 core:backspace (input.hidden-input)
     -2:42.7.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
fix-indent-on-paste 0.1.1 
```

**Comment by patstew** [comment]
I'm afraid that I don't use Atom anymore (VS Code is better), so it's possible that changes in Atom in the last 2 years have broken this extension. Paste without reformatting is now built in atom/atom#15976 so you could use that instead.
I don't think the strange indent on paste is ever going to be fixed, apparently that's how the Atom developers like it https://discuss.atom.io/t/copy-paste-indent-wrong-how-to-fix/58694 and the bug has been closed atom/atom#5473.
If anybody would like to take over maintaining this extension they're more than welcome, I'm sorry but I won't be working on it in future.
